# Generated by Django 5.2.4 on 2026-07-21 12:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120, verbose_name='nome')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='codigo')),
                ('city', models.CharField(max_length=80, verbose_name='cidade')),
                ('state', models.CharField(max_length=2, verbose_name='UF')),
            ],
            options={
                'verbose_name': 'filial',
                'verbose_name_plural': 'filiais',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='EquipmentCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='nome')),
                ('description', models.TextField(blank=True, verbose_name='descricao')),
            ],
            options={
                'verbose_name': 'categoria de equipamento',
                'verbose_name_plural': 'categorias de equipamento',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('legal_name', models.CharField(max_length=150, verbose_name='razao social')),
                ('cnpj', models.CharField(max_length=18, unique=True, verbose_name='CNPJ')),
                ('contact_name', models.CharField(blank=True, max_length=120, verbose_name='contato')),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=30, verbose_name='telefone')),
            ],
            options={
                'verbose_name': 'fornecedor',
                'verbose_name_plural': 'fornecedores',
                'ordering': ('legal_name',),
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120, verbose_name='nome')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='departments', to='organization.branch', verbose_name='filial')),
            ],
            options={
                'verbose_name': 'setor',
                'verbose_name_plural': 'setores',
                'ordering': ('name',),
                'unique_together': {('name', 'branch')},
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('full_name', models.CharField(max_length=150, verbose_name='nome completo')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('job_title', models.CharField(max_length=120, verbose_name='cargo')),
                ('is_active', models.BooleanField(default=True, verbose_name='ativo')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='employees', to='organization.branch', verbose_name='filial')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='employees', to='organization.department', verbose_name='setor')),
            ],
            options={
                'verbose_name': 'colaborador',
                'verbose_name_plural': 'colaboradores',
                'ordering': ('full_name',),
            },
        ),
    ]
