# Generated by Django 5.2.4 on 2026-07-21 17:05

from django.db import migrations, models


def migrate_department_branches(apps, schema_editor):
    Department = apps.get_model("organization", "Department")
    Employee = apps.get_model("organization", "Employee")
    ServiceOrder = apps.get_model("supportdesk", "ServiceOrder")
    KanbanTask = apps.get_model("kanban", "KanbanTask")
    DepartmentBranch = Department.branches.through

    primary_departments_by_name = {}

    for department in Department.objects.order_by("name", "id"):
        primary = primary_departments_by_name.get(department.name)
        if primary is None:
            primary_departments_by_name[department.name] = department
            primary = department

        DepartmentBranch.objects.get_or_create(
            department_id=primary.id,
            branch_id=department.branch_id,
        )

        if primary.id == department.id:
            continue

        Employee.objects.filter(department_id=department.id).update(department_id=primary.id)
        ServiceOrder.objects.filter(department_id=department.id).update(department_id=primary.id)
        KanbanTask.objects.filter(department_id=department.id).update(department_id=primary.id)
        department.delete()


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0001_initial'),
        ('supportdesk', '0001_initial'),
        ('kanban', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='department',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='department',
            name='branches',
            field=models.ManyToManyField(related_name='departments', to='organization.branch', verbose_name='filiais'),
        ),
        migrations.RunPython(migrate_department_branches, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name='department',
            constraint=models.UniqueConstraint(fields=('name',), name='unique_department_name'),
        ),
        migrations.RemoveField(
            model_name='department',
            name='branch',
        ),
    ]
