# Generated by Django 5.2.4 on 2026-07-27 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0002_alter_department_unique_together_department_branches_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='e-mail'),
        ),
        migrations.AddConstraint(
            model_name='employee',
            constraint=models.UniqueConstraint(condition=models.Q(models.Q(('email', None), _negated=True), models.Q(('email', ''), _negated=True)), fields=('email',), name='unique_non_blank_employee_email'),
        ),
    ]
