# Generated by Django 6.1 on 2026-08-20 17:33

from django.db import migrations, models


def populate_employee_codes(apps, schema_editor):
    Employee = apps.get_model('organization', 'Employee')
    current_code = 1
    for employee in Employee.objects.all().order_by('id'):
        if not employee.code:
            employee.code = current_code
            employee.save(update_fields=['code'])
            current_code += 1


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0003_alter_employee_email_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employee',
            options={'ordering': ('code', 'full_name'), 'verbose_name': 'colaborador', 'verbose_name_plural': 'colaboradores'},
        ),
        migrations.AddField(
            model_name='employee',
            name='code',
            field=models.PositiveIntegerField(blank=True, help_text='Código identificador único sequencial gerado automaticamente a partir do número 1.', null=True, unique=True, verbose_name='código'),
        ),
        migrations.RunPython(populate_employee_codes, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='branch',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Criado em'),
        ),
        migrations.AlterField(
            model_name='branch',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Atualizado em'),
        ),
        migrations.AlterField(
            model_name='department',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Criado em'),
        ),
        migrations.AlterField(
            model_name='department',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Atualizado em'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Criado em'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Atualizado em'),
        ),
        migrations.AlterField(
            model_name='equipmentcategory',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Criado em'),
        ),
        migrations.AlterField(
            model_name='equipmentcategory',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Atualizado em'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Criado em'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Atualizado em'),
        ),
    ]
