# Generated by Django 5.2.4 on 2026-07-21 12:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0001_initial'),
        ('organization', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=160, verbose_name='titulo')),
                ('short_description', models.CharField(max_length=255, verbose_name='descricao curta')),
                ('solution_description', models.TextField(verbose_name='solucao aplicada')),
                ('service_datetime', models.DateTimeField(verbose_name='data/hora do servico')),
                ('status', models.CharField(choices=[('open', 'Aberto'), ('in_progress', 'Em Atendimento'), ('done', 'Concluido')], default='done', max_length=20, verbose_name='status')),
                ('attended_user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='service_orders_as_customer', to='organization.employee', verbose_name='usuario atendido')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='service_orders', to='organization.branch', verbose_name='filial')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='service_orders', to='organization.department', verbose_name='setor')),
                ('technician', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='service_orders_as_technician', to='organization.employee', verbose_name='tecnico responsavel')),
            ],
            options={
                'verbose_name': 'ordem de servico',
                'verbose_name_plural': 'ordens de servico',
                'ordering': ('-service_datetime',),
            },
        ),
        migrations.CreateModel(
            name='ServiceOrderItemUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('usage_type', models.CharField(choices=[('equipment', 'Equipamento Envolvido'), ('part', 'Peca/Item Consumido')], default='equipment', max_length=20, verbose_name='tipo de uso')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='quantidade')),
                ('stock_processed', models.BooleanField(default=False, editable=False)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='service_usages', to='inventory.inventoryitem', verbose_name='item')),
                ('service_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_usages', to='supportdesk.serviceorder', verbose_name='ordem de servico')),
            ],
            options={
                'verbose_name': 'item utilizado no servico',
                'verbose_name_plural': 'itens utilizados no servico',
            },
        ),
    ]
