# Generated by Django 5.2.4 on 2026-07-21 12:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organization', '0001_initial'),
        ('procurement', '0001_initial'),
        ('supportdesk', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='KanbanTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=160, verbose_name='titulo')),
                ('description', models.TextField(verbose_name='descricao detalhada')),
                ('priority', models.CharField(choices=[('low', 'Baixa'), ('medium', 'Media'), ('high', 'Alta'), ('urgent', 'Urgente')], default='medium', max_length=10, verbose_name='prioridade')),
                ('due_date', models.DateField(blank=True, null=True, verbose_name='prazo')),
                ('status', models.CharField(choices=[('todo', 'A Fazer'), ('in_progress', 'Em Andamento'), ('waiting', 'Pendente / Aguardando'), ('done', 'Concluido')], default='todo', max_length=20, verbose_name='status')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='ordem')),
                ('assignee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kanban_tasks', to='organization.employee', verbose_name='responsavel')),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kanban_tasks', to='organization.branch', verbose_name='filial')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kanban_tasks', to='organization.department', verbose_name='setor')),
                ('linked_purchase_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kanban_tasks', to='procurement.purchaseorder', verbose_name='compra vinculada')),
                ('linked_service_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kanban_tasks', to='supportdesk.serviceorder', verbose_name='ordem de servico vinculada')),
            ],
            options={
                'verbose_name': 'tarefa do kanban',
                'verbose_name_plural': 'tarefas do kanban',
                'ordering': ('status', 'sort_order', '-created_at'),
            },
        ),
    ]
