# Generated by Django 5.2.4 on 2026-07-21 12:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organization', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=150, verbose_name='nome')),
                ('model', models.CharField(blank=True, max_length=120, verbose_name='modelo')),
                ('brand', models.CharField(blank=True, max_length=120, verbose_name='marca')),
                ('serial_number', models.CharField(blank=True, max_length=120, verbose_name='numero de serie')),
                ('asset_tag', models.CharField(blank=True, max_length=120, verbose_name='patrimonio')),
                ('status', models.CharField(choices=[('in_stock', 'Em Estoque'), ('in_use', 'Em Uso'), ('in_maintenance', 'Em Manutencao'), ('discarded', 'Descartado')], default='in_stock', max_length=20, verbose_name='status')),
                ('quantity', models.PositiveIntegerField(default=0, verbose_name='quantidade em estoque')),
                ('minimum_quantity', models.PositiveIntegerField(default=0, verbose_name='quantidade minima')),
                ('notes', models.TextField(blank=True, verbose_name='observacoes')),
                ('assigned_employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_inventory_items', to='organization.employee', verbose_name='colaborador vinculado')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inventory_items', to='organization.branch', verbose_name='filial')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inventory_items', to='organization.equipmentcategory', verbose_name='categoria')),
            ],
            options={
                'verbose_name': 'item de estoque',
                'verbose_name_plural': 'itens de estoque',
                'ordering': ('name', 'brand', 'model'),
            },
        ),
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('movement_type', models.CharField(choices=[('entry', 'Entrada'), ('exit', 'Saida'), ('adjustment', 'Ajuste'), ('purchase', 'Compra'), ('service_usage', 'Uso em Servico')], max_length=20, verbose_name='tipo de movimentacao')),
                ('quantity', models.PositiveIntegerField(verbose_name='quantidade')),
                ('reference', models.CharField(blank=True, max_length=160, verbose_name='referencia')),
                ('notes', models.TextField(blank=True, verbose_name='observacoes')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movements', to='inventory.inventoryitem', verbose_name='item')),
            ],
            options={
                'verbose_name': 'movimentacao de estoque',
                'verbose_name_plural': 'movimentacoes de estoque',
                'ordering': ('-created_at',),
            },
        ),
    ]
