# Generated by Django 5.2.4 on 2026-07-21 12:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0001_initial'),
        ('procurement', '0001_initial'),
        ('supportdesk', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockmovement',
            name='purchase_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_movements', to='procurement.purchaseorder', verbose_name='compra'),
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='service_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_movements', to='supportdesk.serviceorder', verbose_name='ordem de servico'),
        ),
        migrations.AddConstraint(
            model_name='inventoryitem',
            constraint=models.UniqueConstraint(condition=models.Q(('serial_number', ''), _negated=True), fields=('serial_number',), name='unique_non_blank_serial_number'),
        ),
        migrations.AddConstraint(
            model_name='inventoryitem',
            constraint=models.UniqueConstraint(condition=models.Q(('asset_tag', ''), _negated=True), fields=('asset_tag',), name='unique_non_blank_asset_tag'),
        ),
    ]
