# Generated by Django 6.1 on 2026-08-20 13:37

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_initial'),
        ('supportdesk', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stockmovement',
            options={'ordering': ('-created_at',), 'verbose_name': 'movimentação de estoque', 'verbose_name_plural': 'movimentações de estoque'},
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='acquisition_date',
            field=models.DateField(blank=True, null=True, verbose_name='data de aquisição'),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='unit_price',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='valor do item (R$)'),
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='acquisition_date',
            field=models.DateField(blank=True, null=True, verbose_name='data de aquisição'),
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='unit_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='valor unitário (R$)'),
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='asset_tag',
            field=models.CharField(blank=True, max_length=120, verbose_name='patrimônio'),
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='minimum_quantity',
            field=models.PositiveIntegerField(default=0, verbose_name='quantidade mínima'),
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='notes',
            field=models.TextField(blank=True, verbose_name='observações'),
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='serial_number',
            field=models.CharField(blank=True, max_length=120, verbose_name='número de série'),
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='status',
            field=models.CharField(choices=[('in_stock', 'Em Estoque'), ('in_use', 'Em Uso'), ('in_maintenance', 'Em Manutenção'), ('discarded', 'Descartado')], default='in_stock', max_length=20, verbose_name='status'),
        ),
        migrations.AlterField(
            model_name='stockmovement',
            name='movement_type',
            field=models.CharField(choices=[('entry', 'Entrada'), ('exit', 'Saída'), ('adjustment', 'Ajuste'), ('purchase', 'Compra'), ('service_usage', 'Uso em Serviço')], max_length=20, verbose_name='tipo de movimentação'),
        ),
        migrations.AlterField(
            model_name='stockmovement',
            name='notes',
            field=models.TextField(blank=True, verbose_name='observações'),
        ),
        migrations.AlterField(
            model_name='stockmovement',
            name='reference',
            field=models.CharField(blank=True, max_length=160, verbose_name='referência'),
        ),
        migrations.AlterField(
            model_name='stockmovement',
            name='service_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_movements', to='supportdesk.serviceorder', verbose_name='ordem de serviço'),
        ),
    ]
