# Generated by Django 6.1 on 2026-10-01 17:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_alter_inventoryitem_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventoryitem',
            name='minimum_quantity',
        ),
    ]
