# Generated by Django 5.2.4 on 2026-07-21 12:56

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0001_initial'),
        ('organization', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=160, verbose_name='titulo')),
                ('purchase_date', models.DateField(verbose_name='data da compra')),
                ('estimated_total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='valor estimado')),
                ('actual_total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='valor real')),
                ('status', models.CharField(choices=[('pending', 'Pendente'), ('approved', 'Aprovado'), ('purchased', 'Comprado'), ('delivered', 'Entregue'), ('canceled', 'Cancelado')], default='pending', max_length=20, verbose_name='status')),
                ('invoice_link', models.URLField(blank=True, verbose_name='link da nota fiscal')),
                ('invoice_file', models.FileField(blank=True, upload_to='invoices/', verbose_name='arquivo da nota fiscal')),
                ('notes', models.TextField(blank=True, verbose_name='observacoes')),
                ('inventory_processed', models.BooleanField(default=False, editable=False)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_orders', to='organization.branch', verbose_name='filial')),
                ('requester', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requested_purchase_orders', to='organization.employee', verbose_name='solicitante')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_orders', to='organization.supplier', verbose_name='fornecedor')),
            ],
            options={
                'verbose_name': 'ordem de compra',
                'verbose_name_plural': 'ordens de compra',
                'ordering': ('-purchase_date', '-created_at'),
            },
        ),
        migrations.CreateModel(
            name='PurchaseOrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('item_name', models.CharField(max_length=150, verbose_name='item/equipamento')),
                ('model', models.CharField(blank=True, max_length=120, verbose_name='modelo')),
                ('brand', models.CharField(blank=True, max_length=120, verbose_name='marca')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='quantidade')),
                ('estimated_unit_price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='valor unitario estimado')),
                ('actual_unit_price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='valor unitario real')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_items', to='organization.equipmentcategory', verbose_name='categoria')),
                ('inventory_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchase_items', to='inventory.inventoryitem', verbose_name='item de estoque vinculado')),
                ('purchase_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='procurement.purchaseorder', verbose_name='ordem de compra')),
            ],
            options={
                'verbose_name': 'item da compra',
                'verbose_name_plural': 'itens da compra',
                'ordering': ('item_name',),
            },
        ),
    ]
